name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.2.1-220.0.dev'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_form_builder: ^9.2.1
  google_generative_ai: ^0.4.0
  url_launcher: ^6.0.20  # Correct indentation
  form_builder_validators: ^9.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.2.0
  firebase_core: ^2.24.2
  google_fonts: ^6.2.0
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1
  flutter_typeahead: ^3.1.3
  table_calendar: ^3.0.6
  image_picker: ^0.8.5+3
  shared_preferences: ^2.2.3
  ionicons: ^0.2.2

flutter:
  uses-material-design: true
  assets:
    - images/studentdigitalguidelogo.png
    - images/jnn.jpg
    - images/ziad.jpg
    - images/fadi.jpg
    - images/birziet.jpg
    - files/courses.json

